language: ruby
install: bundle install --without man
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.5
  - 2.2.0
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
sudo: false
addons:
  code_climate:
    repo_token: a38796ef7bdfcb5028d2e395acdd3e3dcad4e84deeb9b456c80d1032f9d3a5d2
